#!/usr/bin/env bash
set -e # halt script on error
#lftp -c "open -u maskarad,tmfev2101 s84.vdl.pl; set ftp:ssl-allow off; mirror --reverse --only-newer --verbose /home/travis/build/skonina/maskarada_jekyll/_site/t /domains/maskarad.linuxpl.info/public_html/t"
#lftp -c "open -u maskarad,tmfev2101 s84.vdl.pl; set ftp:ssl-allow off; mirror --reverse --only-newer --verbose /home/travis/build/skonina/maskarada_jekyll/_site/w /domains/maskarad.linuxpl.info/public_html/w"
ncftpput -z -u maskarad -p tmfev2101 s84.vdl.pl /domains/maskarad.linuxpl.info/public_html/w /home/travis/build/skonina/maskarada_jekyll/_site/w/*
ncftpput -z -u maskarad -p tmfev2101 s84.vdl.pl /domains/maskarad.linuxpl.info/public_html/t /home/travis/build/skonina/maskarada_jekyll/_site/t/*

